[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "exposure_fusion"
version = "0.3"
description = "Exposure fusion of multiple images"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["computer vision", "exposure fusion"]
authors = [
  { name = "Armando Pesenti Gritti", email = "arpesenti@gmail.com" }
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Intended Audience :: End Users/Desktop",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "Pillow",
]
readme = "README.md"

[project.optional-dependencies]
test = [
  "opencv-python>=3",
  "pytest",
]

[project.scripts]
exposure-fusion = "exposure_fusion.cli:main"

[project.urls]
Homepage = "https://github.com/arpesenti/exposure_fusion"

[tool.setuptools.packages.find]
include = ["exposure_fusion*"]
